
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - spring-cloud-network
    restart: always

  sentinel:
    image: bladex/sentinel-dashboard:latest
    container_name: sentinel
    ports:
      - "8858:8858"
    environment:
      - JAVA_OPTS=-Dserver.port=8858
    networks:
      - spring-cloud-network
    restart: always

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: seata
    ports:
      - "3306:3306"
    networks:
      - spring-cloud-network
    restart: always

  seata-server:
    image: seataio/seata-server:latest
    container_name: seata-server
    environment:
      SEATA_CONFIG_NAME: file:/seata/config/registry
    volumes:
      - ./seata/config:/seata/config
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network
    restart: always
    depends_on:
      - mysql
      - nacos

networks:
  spring-cloud-network:
    driver: bridge