services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - MODE=standalone
    ports:
      - "8848:8848"
    networks:
      - spring-cloud-network
    restart: always

  sentinel:
    image: bladex/sentinel-dashboard:latest
    container_name: sentinel
    ports:
      - "8858:8858"
    environment:
      - JAVA_OPTS=-Dserver.port=8858
    networks:
      - spring-cloud-network
    restart: always

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: seata
    ports:
      - "5432:5432"
    networks:
      - spring-cloud-network
    restart: always

  seata-server:
    image: seataio/seata-server:latest
    container_name: seata-server
    environment:
      SEATA_CONFIG_NAME: file:/seata/config/registry
    volumes:
      - ./seata/config:/seata/config
    ports:
      - "8091:8091"
    networks:
      - spring-cloud-network
    restart: always
    depends_on:
      - postgres
      - nacos

networks:
  spring-cloud-network:
    driver: bridge
